---
title: "Data Stewardship"
format: html
---

<hr>
    
### What is it?
<!-- <br> -->
*Data stewardship is the actions involved in supporting, promoting, and guiding the use and reuse of data throughout the data lifecycle.*

<br>

::: {.commentbox}
::::{.commentbox-header}
Lesson
::::
::::{.commentbox-body}
 
 - [Data Stewardship Lesson](https://doi.org/10.5281/zenodo.21399253)  
    - See also the accompanying "Defining your Why Worksheet", "Stewardship Maturity Assessment", and "Stewardship Actions & Considerations for Software Management Plans (SMPs)" in the [Ocean Data Stewardship Toolkit](https://doi.org/10.5281/zenodo.21397627).   
       
::::
:::
 
<br>

### Why does data stewardship matter? 
<!-- <br> -->

 * enables faster, better science
 * connects your data to new insights
 * gets you credit for your data work
 * preserves knowledge for the future

<br>

### Defining your "why" for data stewardship
<!-- <br> -->
When thinking about why you might practice data stewardship, consider

 * Who might use your data?
 * What might be the impact of your data?
 * What would make your data or project a success?
 
<br>

### Additional resources

See the [Data Stewardship](resources.qmd#data-stewardship) section of the Resources page for more information.    
