---
title: "About"
format: html
---

<br>

Ocean data is critical for the science, innovation, and management we need for a livable planet, but too often data is trapped in organizational silos and on local hard drives. Unlocking ocean data is not a technology problem; it’s about *supporting the people who* apply expertise, judgment, and skill to *connect data to action* throughout the data lifecycle. *We call this ocean data stewardship*, and we think it's an essential superpower, especially in a moment when the global data landscape is rapidly changing.

<br>

Data stewardship is a proactive mindset that makes data actionable. Data stewards improve the value and impact of ocean data by practicing stewardship throughout the data lifecycle. By treating data as a community asset, ocean data stewards increase the reach of data beyond any single project and expand the body of knowledge available to everyone.

<br>

### Train with us!

Intertidal Agency's [Ocean Data Stewardship training program](training-program.qmd) seeks to build a global community of ocean data stewards who are active in making ocean data more reusable and used for action.  

<br> 

