---
title: "Planning"
format: html
---

<hr>

### What is it? 

*Planning for the implementation of data stewardship practices and actions throughout the data lifecycle is critical to making data reusable.  This can be as simple as keeping a "decision log" in a text document to track process and decisions.  It can also include creating Data Management Plans (DMPs), making data ready for action, and ensuring data and metadata quality.*  
<br>

::: {.commentbox}
::::{.commentbox-header}
Lessons
::::
::::{.commentbox-body}

 - [DMP Lesson](https://doi.org/10.5281/zenodo.21421868) and exercise
 - [Data Ready for Action Lesson](https://doi.org/10.5281/zenodo.21421924) 

::::
:::
 
<br> 

### Data Management Plans (DMPs)

A DMP is a formal document that outlines the data, code, and other products you will produce and how you will format, document, store, and preserve them both during and after the project

DMPs are part of the technical documentation that supports your data stewardship goals, and can be related to project roadmaps, technical work plans, and data governance strategies.  

<br>

### Data fit for purpose

Planning stewardship actions that will make data ready to meet your goals and address your "why" will result in data that is ready to be used.  
Consider key questions like…

 - Who is your data for and what do they need your data to do?
 - What does success look like… for you, your team, and the community?
 - What else could your data do?

<br>

### Other related planning topics

Software Management Plans are another important tool.  Please see the [Ocean Data Stewardship Toolkit](https://doi.org/10.5281/zenodo.21397627) for more on planning for software management. 
<br>

### Additional resources

See the [Data Management Plans](resources.qmd#Data Management Plans (DMPs)) section of the Additional Resources page for more information.  


