---
title: "Publishing Data in Repositories"
format: html
---

<hr>

### What is it?

*Publishing data is the process of packaging up data and descriptive metadata, attaching a persistent identifier (e.g. DOI), and making available through a data repository (an entity that provides long-term storage and access to data).*   

<br>

::: {.commentbox}
::::{.commentbox-header}
Lessons
::::
::::{.commentbox-body}

 - [Data Publishing Basics Lesson](https://doi.org/10.5281/zenodo.21421189)

 - [Data Repositories Lesson](https://doi.org/10.5281/zenodo.21421310)
 
 - Zenodo Clinic developed for [Openscapes](https://openscapes.org/): [slides](https://docs.google.com/presentation/d/1oPqhpq8_v1CUIyOnh6iJA8VcJ9qZXFhmlmmym4jF1cA/) and [recording](https://youtu.be/iO5MFytA2B0) (25 mins)

::::
:::
 
<br>

### TRUST Principles for data repositories

The TRUST Principles are a set of guidelines developed to ensure that digital data repositories are reliable, sustainable, and useful over the long term, and include the following: 

 - Transparency
 - Responsibility
 - User focus
 - Sustainability
 - Technology

<br>

### Additional resources

See the [Repositories](resources.qmd#repositories) section of the Resources page for more information.    
 